[project]
name = 'template'
description = 'git based project templates'
readme = 'README.md'
license = 'MIT'
dynamic = ['version']
dependencies = ['combustache']

[project.optional-dependencies]
dev = ['ruff', 'faterunner']

[project.scripts]
template = 'template:_cli'

[tool.ruff]
line-length = 79
[tool.ruff.format]
quote-style = 'single'
[tool.ruff.lint]
extend-select = ['I', 'E501']

[tool.faterunner.targets]
check = ['ruff check .', 'ruff format --check .']
format = ['ruff check --fix .', 'ruff format .']

[tool.hatch.version]
path = 'template.py'

[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'
